CREATE TABLE users
(id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 login VARCHAR(20) NOT NULL,
 password VARCHAR(255) NOT NULL,
 seed VARCHAR(255) NOT NULL);

ALTER TABLE users 
ADD CONSTRAINT login_unique UNIQUE(login);